name:
channels:
  - conda-forge
  - bioconda
  - fastai
dependencies:
  - python=3.10
  - ca-certificates
  - openssl
  - python-dotenv
  - ipykernel
  - papermill # for running notebooks on CLI with parameters
  - jupyter
  - nbdev